name: Build and Push Docker
on:
  release:
    types:
      - created
  push:
    branches:
      - main
jobs:
  push:
    strategy:
      matrix:
        package: [web, workers]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.package }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          target: ${{ matrix.package }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/mohamedbassem/hoarder-${{ matrix.package }}:latest
          cache-from: type=registry,ref=ghcr.io/mohamedbassem/hoarder-build-cache:${{ matrix.package }}
          cache-to: type=registry,mode=max,ref=ghcr.io/mohamedbassem/hoarder-build-cache:${{ matrix.package }}

      - name: Build ${{ matrix.package }} (release)
        uses: docker/build-push-action@v5
        if: github.event_name == 'release'
        with:
          context: .
          file: docker/Dockerfile
          target: ${{ matrix.package }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/mohamedbassem/hoarder-${{ matrix.package }}:${{ github.event.release.name }},ghcr.io/mohamedbassem/hoarder-${{ matrix.package }}:release
          cache-from: type=registry,ref=ghcr.io/mohamedbassem/hoarder-build-cache:${{ matrix.package }}
          cache-to: type=registry,mode=max,ref=ghcr.io/mohamedbassem/hoarder-build-cache:${{ matrix.package }}
